### ISSUE TITLE
Data not reporting to Newrelic 

### ISSUE THREAD

**Issue by Santu439** [newrelic/newrelic-unix-monitor#40]
Hi Team,

Can you help me with this issue. have added the integration and updated proxy however data is not getting reported to NewRelic.

Below are the logs, have verified with our network team and found no issue with firewall

Please note, I've replaced actual server name with worrd "hostname" & account number with xxxxx for privacy.

plugin.log:
2022-05-16 04:09:17 [main] INFO c.newrelic.infra.publish.api.Runner - Using account ID: xxxxx
2022-05-16 04:09:17 [main] INFO c.n.infra.unix.UnixAgentFactory - Agentname: hostname_0
2022-05-16 04:09:17 [main] INFO c.n.infra.unix.UnixAgentFactory - Host OS: solaris_10
2022-05-16 04:09:17 [main] INFO c.n.infra.unix.UnixAgentFactory - Hostname: hostname
2022-05-16 04:09:17 [main] INFO c.n.i.p.insights.InsightsRunner - Using Data Center: US
2022-05-16 04:09:17 [main] INFO c.n.i.p.insights.InsightsRunner - Using Insights API URL: https://insights-collector.newrelic.com/v1/accounts/xxxxxx/events
2022-05-16 04:09:17 [main] INFO c.n.i.p.insights.InsightsRunner - Using pollInterval 60
2022-05-16 04:09:18 [main] INFO c.n.i.p.insights.InsightsRunner - INFO: New Relic monitor started
2022-05-16 04:09:24 [pool-2-thread-1] ERROR c.n.insights.publish.InsightsClient - insights-collector.newrelic.com
2022-05-16 04:09:24 [pool-2-thread-1] ERROR c.n.i.p.insights.InsightsRunner - Error posting events to Insights for agent: hostname
2022-05-16 04:10:24 [pool-2-thread-1] ERROR c.n.insights.publish.InsightsClient - insights-collector.newrelic.com
2022-05-16 04:10:24 [pool-2-thread-1] ERROR c.n.i.p.insights.InsightsRunner - Error posting events to Insights for agent: hostname
2022-05-16 04:11:23 [pool-2-thread-1] ERROR c.n.insights.publish.InsightsClient - insights-collector.newrelic.com
2022-05-16 04:11:23 [pool-2-thread-1] ERROR c.n.i.p.insights.InsightsRunner - Error posting events to Insights for agent: hostname
2022-05-16 04:12:23 [pool-2-thread-1] ERROR c.n.insights.publish.InsightsClient - insights-collector.newrelic.com
2022-05-16 04:12:23 [pool-2-thread-1] ERROR c.n.i.p.insights.InsightsRunner - Error posting events to Insights for agent: hostname
2022-05-16 04:13:23 [pool-2-thread-1] ERROR c.n.insights.publish.InsightsClient - insights-collector.newrelic.com
2022-05-16 04:13:23 [pool-2-thread-1] ERROR c.n.i.p.insights.InsightsRunner - Error posting events to Insights for agent: hostname
2022-05-16 04:14:23 [pool-2-thread-1] ERROR c.n.insights.publish.InsightsClient - insights-collector.newrelic.com
2022-05-16 04:14:23 [pool-2-thread-1] ERROR c.n.i.p.insights.InsightsRunner - Error posting events to Insights for agent: hostname
2022-05-16 04:15:23 [pool-2-thread-1] ERROR c.n.insights.publish.InsightsClient - insights-collector.newrelic.com
2022-05-16 04:15:23 [pool-2-thread-1] ERROR c.n.i.p.insights.InsightsRunner - Error posting events to Insights for agent: hostname
2022-05-16 04:16:23 [pool-2-thread-1] ERROR c.n.insights.publish.InsightsClient - insights-collector.newrelic.com
2022-05-16 04:16:23 [pool-2-thread-1] ERROR c.n.i.p.insights.InsightsRunner - Error posting events to Insights for agent: hostname
2022-05-16 04:17:23 [pool-2-thread-1] ERROR c.n.insights.publish.InsightsClient - insights-collector.newrelic.com
2022-05-16 04:17:23 [pool-2-thread-1] ERROR c.n.i.p.insights.InsightsRunner - Error posting events to Insights for agent: hostname
2022-05-16 04:18:23 [pool-2-thread-1] ERROR c.n.insights.publish.InsightsClient - insights-collector.newrelic.com
2022-05-16 04:18:23 [pool-2-thread-1] ERROR c.n.i.p.insights.InsightsRunner - Error posting events to Insights for agent: hostname
2022-05-16 04:19:23 [pool-2-thread-1] ERROR c.n.insights.publish.InsightsClient - insights-collector.newrelic.com
2022-05-16 04:19:23 [pool-2-thread-1] ERROR c.n.i.p.insights.InsightsRunner - Error posting events to Insights for agent: hostname

plugin.err:

####################
Starting New Relic Unix Monitor
Host OS: SunOS
Java location: /usr/jdk/instances/jdk1.6.0//bin/java
Java version: java version "1.6.0_211"
Java(TM) SE Runtime Environment (build 1.6.0_211-b11)
Java HotSpot(TM) Server VM (build 20.211-b11, mixed mode)
Plugin location: /opt/newrelic/newrelic-unix-monitor
Plugin startup command: /usr/jdk/instances/jdk1.6.0//bin/java -Xms16m -Xmx128m -Dnewrelic.platform.service.mode=Insights -Dlogback.configurationFile=config/logback.xml -cp /opt/newrelic/newrelic-unix-monitor/lib/newrelic-unix-monitor.jar com.newrelic.infra.unix.Main
java.net.UnknownHostException: insights-collector.newrelic.com
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:905)
	at java.net.InetAddress.getAddressFromNameService(InetAddress.java:1258)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1209)
	at java.net.InetAddress.getAllByName(InetAddress.java:1139)
	at java.net.InetAddress.getAllByName(InetAddress.java:1075)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.newrelic.insights.publish.InsightsClient.post(InsightsClient.java:91)
	at com.newrelic.infra.publish.insights.InsightsRunner$PollAgentsRunnable.run(InsightsRunner.java:212)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:317)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:150)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.runPeriodic(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:204)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:905)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:928)
	at java.lang.Thread.run(Thread.java:682)

**Comment by Santu439** [comment]
Syntax error for proxy settings
