### ISSUE TITLE
r1.0.1 -- Unsupported major.minor version 51.0 

### ISSUE THREAD

**Issue by AshStirling** [newrelic/newrelic-unix-monitor#52]
Hello,

  I am attempting to run the 1.0.1 release of the monitor on a SunOS 5.10 box that has Java 1.6, but it is complaining that the major.minor version is unsupported.  Please see the contents of the plugin.err below:

```
####################
Starting New Relic Unix Monitor
Host OS: SunOS
Java location: /usr/bin/java
Java version: java version "1.6.0_181"
Java(TM) SE Runtime Environment (build 1.6.0_181-b10)
Java HotSpot(TM) Server VM (build 20.181-b10, mixed mode)
Plugin location: /opt/monitor/newrelic-unix-monitor
Plugin startup command: /usr/bin/java -Xms16m -Xmx128m -Dnewrelic.platform.service.mode=Insights -Dlogback.configurationFile=config/logback-debug.xml -cp /opt/monitor/newrelic-unix-monitor/lib/newrelic-unix-monitor.jar com.newrelic.infra.unix.Main
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/newrelic/infra/unix/Main : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:304)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:56)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:218)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:211)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Could not find the main class: com.newrelic.infra.unix.Main.  Program will exit.
```

Did the JDK requirement change with the latest release?

Thanks,
- Ash

**Comment by gsidhwani-nr** [comment]
Hello Ash,
Yes, Minimum JDK version required is 1.8 .

Thanks
Gulab

**Comment by AshStirling** [comment]
Ok, thanks for confirming.  The requirements section in the README.md has this still listed as 1.6.

Thanks,
Ash
