### ISSUE TITLE
Error in logs/plugin.err

### ISSUE THREAD

**Issue by rwun** [newrelic/newrelic-unix-monitor#8]
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "uuid" (class com.newrelic.insights.publish.InsightsResponse), not marked as ignorable (one known property: "success"])
 at [Source: java.io.BufferedReader@30fc1f; line: 1, column: 26] (through reference chain: com.newrelic.insights.publish.InsightsResponse["uuid"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:52)
	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:839)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1045)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1352)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1330)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:264)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2773)
	at com.newrelic.insights.publish.InsightsClient.post(InsightsClient.java:86)
	at com.newrelic.infra.publish.insights.InsightsRunner$PollAgentsRunnable.run(InsightsRunner.java:163)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:317)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:150)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.runPeriodic(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:204)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:680)

**Comment by rwun** [comment]
I am not getting values for Memory under unixMonitor:Stats.

**Comment by sschwartzman** [comment]
@rwun - we've implemented a fix for this exception. The latest release (0.1.4) contains that fix. Can you try it out and confirm? https://github.com/newrelic/newrelic-unix-monitor/releases/tag/0.1.4

**Comment by rwun** [comment]
Yes, confirmed.  No more exceptions with the latest version.
